#!/usr/bin/env bash
set -euo pipefail

echo "=== Preparing Windows Ephemeral Build Cache ==="

# 1. Create target directories
EPHEMERAL_DIR="windows/flutter/ephemeral"
WRAPPER_DIR="${EPHEMERAL_DIR}/cpp_client_wrapper"
mkdir -p "${WRAPPER_DIR}/include/flutter"

# 2. Copy Engine binaries and headers
echo "Copying Flutter Engine files from xyz.maya/tmp_engine..."
cp xyz.maya/tmp_engine/flutter_windows.dll "${EPHEMERAL_DIR}/"
cp xyz.maya/tmp_engine/flutter_windows.dll.lib "${EPHEMERAL_DIR}/"
cp xyz.maya/tmp_engine/flutter_export.h "${EPHEMERAL_DIR}/"
cp xyz.maya/tmp_engine/flutter_windows.h "${EPHEMERAL_DIR}/"
cp xyz.maya/tmp_engine/flutter_messenger.h "${EPHEMERAL_DIR}/"
cp xyz.maya/tmp_engine/flutter_plugin_registrar.h "${EPHEMERAL_DIR}/"
cp xyz.maya/tmp_engine/flutter_texture_registrar.h "${EPHEMERAL_DIR}/"

# 3. Copy platform-independent ICU data
echo "Copying ICU database (icudtl.dat) from Flutter SDK..."
cp /home/ruggedcoder/flutter/flutter/bin/cache/artifacts/engine/linux-x64/icudtl.dat "${EPHEMERAL_DIR}/"

# 4. Copy C++ client wrapper source files (common & windows)
echo "Harvesting C++ Client Wrapper sources..."
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/common/client_wrapper/core_implementations.cc "${WRAPPER_DIR}/"
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/common/client_wrapper/standard_codec.cc "${WRAPPER_DIR}/"
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/common/client_wrapper/plugin_registrar.cc "${WRAPPER_DIR}/"
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/windows/client_wrapper/flutter_engine.cc "${WRAPPER_DIR}/"
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/windows/client_wrapper/flutter_view_controller.cc "${WRAPPER_DIR}/"
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/common/client_wrapper/*.h "${WRAPPER_DIR}/"

# 5. Copy C++ client wrapper headers
echo "Harvesting C++ Client Wrapper headers..."
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/common/client_wrapper/include/flutter/* "${WRAPPER_DIR}/include/flutter/"
cp /home/ruggedcoder/flutter/flutter/engine/src/flutter/shell/platform/windows/client_wrapper/include/flutter/* "${WRAPPER_DIR}/include/flutter/"

# 6. Generate ephemeral config cmake
echo "Generating generated_config.cmake..."
cat << 'EOF' > "${EPHEMERAL_DIR}/generated_config.cmake"
# Generated by Antigravity offline compiler script
set(FLUTTER_ROOT "/home/ruggedcoder/flutter/flutter" CACHE INTERNAL "Path to Flutter SDK")
set(FLUTTER_TARGET "/home/ruggedcoder/softwares/fresh/anydb_flutter/lib/main.dart" CACHE INTERNAL "Path to main.dart")
set(PROJECT_DIR "/home/ruggedcoder/softwares/fresh/anydb_flutter" CACHE INTERNAL "Path to project directory")
set(FLUTTER_TARGET_PLATFORM "windows-x64" CACHE INTERNAL "Target platform")
set(FLUTTER_VERSION "1.0.0" CACHE INTERNAL "Flutter Version")
set(FLUTTER_VERSION_MAJOR "1" CACHE INTERNAL "Flutter Version Major")
set(FLUTTER_VERSION_MINOR "0" CACHE INTERNAL "Flutter Version Minor")
set(FLUTTER_VERSION_PATCH "0" CACHE INTERNAL "Flutter Version Patch")
set(FLUTTER_VERSION_BUILD "0" CACHE INTERNAL "Flutter Version Build")
EOF

echo "=== Ephemeral Cache Setup Complete! ==="
